import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/configs/font.config';
import { AuthProvider } from '@/context/auth.context';
import { Toaster } from '@/components/ui/sonner';
import { QueryProvider } from '@/context/query.context';
import Header from './_components/Header';
import { ThemeProvider } from '@/context/theme.context';
import { DEFAULT_LANGUAGE } from '@/configs/messages.config';

export const metadata: Metadata = {
  title: 'Data gen hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={DEFAULT_LANGUAGE} suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Header />
            {children} <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
