import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/configs/font.config';
import { AuthProvider } from '@/context/auth.context';

export const metadata: Metadata = {
  title: 'Data gen hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
